name: Publish PR middleware with commit hash

on:
  push:
    paths:
      - 'plugins/**'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1 
        with:
          format: ''

      - name: File tree
        run: |
          sudo apt install -y tree
          tree .

      - name: Build deployable zip file using docker
        run: |
          plugins=()
          for file in ${{ steps.files.outputs.all }}; do
            plugins+=($(echo "$file" | cut -d \/ -f 2));
          done;
          echo $plugins;

