name: Publish PR middleware with commit hash

on:
  push:
    paths:
      - 'plugins/**'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: File tree
        run: |
          apt install -y tree
          tree .

      - name: Build deployable zip file using docker
        run: |
          version=$(git log -1 --format="%h")
          echo version=$version

