name: Build PR of first plugin

on:
  pull_request:
    paths:
      - 'plugins/**'
  push:
    paths:
      - 'plugins/**'

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: [first, second]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get patch files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: success step
        run: echo "hello"; exit 0;

      - name: force fail step
        id: force-fail
        run: |
          echo "hello";
          echo "::set-output name=cancel-step::true"
          exit 1;
        continue-on-error: true

      - name: based on prev decision step
        if: success()
        run: echo "seems all previous steps are succeeded"; exit 0;

      - name: always run me
        if: always()
        run: echo "hello"; exit 0;

      - name: basic step
        if: steps.force-fail.outputs.cancel-step == 'true'
        run: echo "hello world";




      - name: Check added/modified bundle files
        id: check-files
        run: |
          echo "Files: ${{steps.files.outputs.added_modified}}"
          if [[ "${{steps.files.outputs.added_modified}}" == *"${{matrix.plugin}}"* ]]; then
            echo "Continue processing plugin..."
            echo "::set-output name=continue::further"
          else
            echo "No patch files detected for the plugin"
            echo "Cancel the workflow!"
          fi

      - name: Compress and upload bundle
        if: github.steps.check-files.outputs.continue == 'further'
        run: |
          version=$(git log -1 --format="%h")
          docker run --rm -v $(pwd)/plugins/${{matrix.plugin}}:/plugin \
            --entrypoint "/bin/sh" \
            -w "/plugin" tykio/tyk-gateway:v4.0 \
            -c "/opt/tyk-gateway/tyk bundle build -y"

          mv plugins/${{matrix.plugin}}/bundle.zip ${{matrix.plugin}}-$version.zip

          # push file to Nexus here <-

      - name: Tree step
        run: sudo apt install -y tree; tree .
