name: Build PR of first plugin

on:
  pull_request:
    paths:
      - 'plugins/**'
  push:
    paths:
      - 'plugins/**'
      - '!plugins/README.md'

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: [first, second, response-hook]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get patch files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Check added/modified bundle files
        run: |
          echo -e "Files: ${{steps.files.outputs.added_modified}}\n"
          if grep -q "${{matrix.plugin}}" <<< "${{steps.files.outputs.added_modified}}"; then
            echo "Continue processing plugin..."
            exit 0
          else
            echo "No patch files detected for the plugin"
            echo "Cancel the workflow!"
            exit 1
          fi

      - name: Compress and upload bundle
        if: success()
        run: |
          version=$(git log -1 --format="%h")
          docker run --rm -v $(pwd)/plugins/${{matrix.plugin}}:/plugin \
            --entrypoint "/bin/sh" \
            -w "/plugin" tykio/tyk-gateway:v4.0 \
            -c "/opt/tyk-gateway/tyk bundle build -y"

          mv plugins/${{matrix.plugin}}/bundle.zip ${{matrix.plugin}}-$version.zip

          sudo apt install -y tree
          tree .

          # push file to Nexus here <-

          echo -e "\nBundle name: ${{matrix.plugin}}-$version.zip\n"
