name: Publish PR middleware with commit hash

on:
  push:
    paths:
      - 'plugins/**'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - id: files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: File tree
        run: |
          sudo apt install -y tree
          tree .

      - name: Build deployable zip file using docker
        run: |
          version=$(git log -1 --format="%h")
          echo version=$version
          for file in ${{ steps.files.outputs.all }}:
            ls -l "$file";
          done

