name: Build PR of first plugin

on:
  pull_request:
    paths:
      - 'plugins/**'
  push:
    paths:
      - 'plugins/**'

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: [first, second]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get patch files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Check for cancelation
        run: |
          echo "Commit 'added_modified' files: ${{steps.files.outputs.added_modified}}"
          if [[ "${{steps.files.outputs.added_modified}}" == *"${{matrix.plugin}}"* ]]; then
            echo "Continue processing '${{matrix.plugin}}'..."
            exit 0;
          else
            echo "No patch files detected for the '${{matrix.plugin}}' plugin"
            echo "Cancel the workflow!"
            exit 1;
          fi

      - name: Compress and upload bundle
        if: ${{success()}}
        run: |
          version=$(git log -1 --format="%h")
          docker run --rm -v $(pwd)/plugins/${{matrix.plugin}}:/plugin \
            --entrypoint "/bin/sh" \
            -w "/plugin" tykio/tyk-gateway:v4.0 \
            -c "/opt/tyk-gateway/tyk bundle build -y"

          mv plugins/${{matrix.plugin}}/bundle.zip ${{matrix.plugin}}-$version.zip

          sudo apt install -y tree
          tree .

          # push file to Nexus here <-



#       - name: Specify plugin to compress
#         id: plugins-names
#         with:
#           result-encoding: string
#         run: |
#           for file in ${{ steps.files.outputs.added_modified }}; do
#             if [[ "$file" == *"plugins/"* ]]; then
#               echo "$file" | cut -d \/ -f 2;
#             fi;
#           done

#       - name: Check if multiple plugins
#         if: {{ steps.plugins-names.output. }}

#       - name: Create & upload the bundle
#         run: |
#           docker run --rm -v $(pwd):/plugin --entrypoint "/bin/sh" -w "/plugin" tykio/tyk-gateway:v4.0 -c "/opt/tyk-gateway/tyk bundle build -y"
#           mv bundle.zip bundle-$version.zip
#           curl -v --connect-timeout 2 --speed-time 10 --speed-limit 10000 -u github:${{ secrets.NEXUS_PASSWORD }} \
#             --upload-file "$(pwd)/bundle-$version.zip" "https://nexus.services.bwell.zone/repository/tyk-middleware/"

# GetUniquePluginNames () {
# for file in $(echo "plugins/second/middleware.lua plugins/first/manifest.json plugins/first/middleware.py"); do
#   if [[ "$file" == *"plugins/"* ]]; then
#     echo $file | cut -d \/ -f 2
#     # plugins+=" $(echo $file | cut -d \/ -f 2)"
#   fi;
# done | uniq
# };

# plugins=GetUniquePluginNames;
# echo $plugins;

