name: Build PR of first plugin

on:
  # pull_request:
  #   paths:
  #     - 'plugins/**'
  push:
    # paths:
    #   - 'plugins/**'

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: [first, second]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get patch files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Check for cancelation
        run: |
          echo "Commit 'added_modified' files: ${{steps.files.outputs.added_modified}}"
          if [[ "${{steps.files.outputs.added_modified}}" == *"${{matrix.plugin}}"* ]]; then
            echo "Continue processing '${{matrix.plugin}}' plugin..."
            exit 0;
          fi
          echo "No patch files detected for the '${{matrix.plugin}}' plugin"
          echo "Cancel the workflow!"
          exit 1;

      - name: Compress and upload bundle
        if: failure()
        run: |
          version=$(git log -1 --format="%h")
          docker run --rm -v $(pwd)/plugins/${{matrix.plugin}}:/plugin \
            --entrypoint "/bin/sh" \
            -w "/plugin" tykio/tyk-gateway:v4.0 \
            -c "/opt/tyk-gateway/tyk bundle build -y"

          mv plugins/${{matrix.plugin}}/bundle.zip ${{matrix.plugin}}-$version.zip

          sudo apt install -y tree
          tree .

          # push file to Nexus here <-
