name: Push to Dev [manual]

on:
  workflow_dispatch:
    inputs:
      plugin-name:
        description: 'Plugin name'
        required: true
        type: choice
        options:
        - first
        - second
        - response-hook 
      version:
        description: 'Version should be uniqie'
        required: true
        type: string

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compress and upload bundle
        run: |
          docker run --rm -v $(pwd)/plugins/${{github.event.inputs.plugin-name}}:/plugin \
            --entrypoint "/bin/sh" \
            -w "/plugin" tykio/tyk-gateway:v4.0 \
            -c "/opt/tyk-gateway/tyk bundle build -y"

          newFileName="${{github.event.inputs.plugin-name}}-${{github.event.inputs.version}}.zip"
          mv plugins/${{github.event.inputs.plugin-name}}/bundle.zip $newFileName

          sudo apt install -y tree
          tree .

          # push file to Nexus here <-

          ls $newFileName
